insert into `tenant_lottery` 
( 	`tenant_code`, 
	`lottery_id`,
	`series_tag`, 
	`name`, 
	`platform_show_status`, 
	`platform_status`,
	`tenant_show_status`, 
	`tenant_status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`,  
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	`init_status`, 
	`game_id`)  
select 
	'CSZHY' as `tenant_code`,
	`id`,
	`series_tag`, 
	`name`, 
	`show_status`, 
	`status`,
	`show_status`, 
	`status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`, 
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	1, 
	`game_id`
from `lottery`
where id in (117,118,119);

insert into `tenant_lottery` 
( 	`tenant_code`, 
	`lottery_id`,
	`series_tag`, 
	`name`, 
	`platform_show_status`, 
	`platform_status`,
	`tenant_show_status`, 
	`tenant_status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`,  
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	`init_status`, 
	`game_id`)  
select 
	'XGCP' as `tenant_code`,
	`id`,
	`series_tag`, 
	`name`, 
	`show_status`, 
	`status`,
	`show_status`, 
	`status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`, 
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	1, 
	`game_id`
from `lottery`
where id in (117,118,119);

insert into `tenant_lottery` 
( 	`tenant_code`, 
	`lottery_id`,
	`series_tag`, 
	`name`, 
	`platform_show_status`, 
	`platform_status`,
	`tenant_show_status`, 
	`tenant_status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`,  
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	`init_status`, 
	`game_id`)  
select 
	'CSZHE' as `tenant_code`,
	`id`,
	`series_tag`, 
	`name`, 
	`show_status`, 
	`status`,
	`show_status`, 
	`status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`, 
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	1, 
	`game_id`
from `lottery`
where id in (117,118,119);

insert into `tenant_lottery` 
( 	`tenant_code`, 
	`lottery_id`,
	`series_tag`, 
	`name`, 
	`platform_show_status`, 
	`platform_status`,
	`tenant_show_status`, 
	`tenant_status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`,  
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	`init_status`, 
	`game_id`)  
select 
	'CSZHS' as `tenant_code`,
	`id`,
	`series_tag`, 
	`name`, 
	`show_status`, 
	`status`,
	`show_status`, 
	`status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`, 
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	1, 
	`game_id`
from `lottery`
where id in (117,118,119);

insert into `tenant_lottery` 
( 	`tenant_code`, 
	`lottery_id`,
	`series_tag`, 
	`name`, 
	`platform_show_status`, 
	`platform_status`,
	`tenant_show_status`, 
	`tenant_status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`,  
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	`init_status`, 
	`game_id`)  
select 
	'TYCC' as `tenant_code`,
	`id`,
	`series_tag`, 
	`name`, 
	`show_status`, 
	`status`,
	`show_status`, 
	`status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`, 
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	1, 
	`game_id`
from `lottery`
where id in (117,118,119);

insert into `tenant_lottery` 
( 	`tenant_code`, 
	`lottery_id`,
	`series_tag`, 
	`name`, 
	`platform_show_status`, 
	`platform_status`,
	`tenant_show_status`, 
	`tenant_status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`,  
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	`init_status`, 
	`game_id`)  
select 
	'CPT' as `tenant_code`,
	`id`,
	`series_tag`, 
	`name`, 
	`show_status`, 
	`status`,
	`show_status`, 
	`status`, 
	`documentary_status`, 
	`sort`, 
	`icon`, 
	`gray_icon`, 
	`explain`, 
	`lottery_type`, 
	`lottery_method`, 
	`kill_number_paramer1`, 
	`kill_number_paramer2`, 
	`kill_number_paramer3`, 
	`kill_number_paramer4`, 
	1, 
	`game_id`
from `lottery`
where id in (117,118,119);